/**
 * Generated by scripts/generate-internal-docs.mjs — do not edit by hand.
 * Index only (small); content is in internalDocsContent.ts for lazy loading.
 */

export type InternalDocEntry = {
  id: string;
  title: string;
  oneLine: string;
};

export const INTERNAL_DOCS_INDEX: InternalDocEntry[] = [
  { id: "getting-started", title: "Getting Started with Helpmaton", oneLine: "Welcome to Helpmaton! This guide will help you get started with using the platform." },
  { id: "agent-configuration", title: "Agent Configuration Guide", oneLine: "This guide covers how to configure and manage agents in Helpmaton." },
  { id: "document-management", title: "Document Management", oneLine: "Helpmaton allows you to upload, organize, and manage documents that can inform your agents' behavior." },
  { id: "workspace-permissions", title: "Workspace Permissions", oneLine: "Helpmaton uses a permission-based system to control access to workspaces and their resources." },
  { id: "api-reference", title: "API Reference", oneLine: "This document provides comprehensive documentation for all Helpmaton API endpoints, including request/response format..." },
  { id: "pricing", title: "Pricing System", oneLine: "This document explains how Helpmaton calculates and charges for LLM API calls, including the integration with OpenRou..." },
  { id: "troubleshooting", title: "Troubleshooting Guide", oneLine: "Common issues and solutions when using Helpmaton." },
  { id: "authentication", title: "Authentication System", oneLine: "This document describes the authentication system in Helpmaton, including session-based authentication, JWT tokens, A..." },
  { id: "subscription-management", title: "Subscription Management", oneLine: "This document describes the subscription system in Helpmaton, including plans, limits, and management rules." },
  { id: "mcp-servers", title: "MCP Server Integration", oneLine: "This document explains how to configure and use MCP (Model Context Protocol) servers in Helpmaton to extend agent cap..." },
  { id: "credit-system", title: "Credit System", oneLine: "This document explains how the credit system works in Helpmaton, including credit reservation, adjustment, spending l..." },
  { id: "webhook-system", title: "Webhook System", oneLine: "This document describes the webhook system in Helpmaton, including endpoint structure, authentication, request/respon..." },
];

/** One line per doc for system prompt: "- [id] title — oneLine" */
export function getInternalDocsIndexForPrompt(): string {
  return INTERNAL_DOCS_INDEX.map(
    (e) => `- [${e.id}] ${e.title} — ${e.oneLine}`
  ).join("\n");
}
