/**
 * Generated by scripts/generate-internal-docs.mjs — do not edit by hand.
 * Re-exports index and content for backward compatibility (e.g. tests).
 */

export * from "./internalDocsIndex";
export * from "./internalDocsContent";
